[providers]
    node = true
    python = true

[phases.setup]
    nixPkgs = ["nodejs_20", "python311", "gcc"]

[phases.install]
    cmds = [
        "npm install --prefix NticPlatform.Frontend",
        "pip install -r requirements.txt"
    ]

[phases.build]
    cmds = [
        "npm run build --prefix NticPlatform.Frontend"
    ]

[start]
    cmd = "python NticPlatform.Backend/run.py"
